arrayfire/arrayfire-rust

Cargo.lock
Cargo.toml
README.md
build.conf
build.rs
src/lib.rs
tests/hello_world.rs

Selective backend building

---

build.conf
build.rs
src/lib.rs

Earlier, all the built backends of ArrayFire submodule were
linked with rust wrapper. This created issues when multiple backends
were linked at the same time.
This commit, adds the option `use_backend` to `build.conf` which
dictates the backend ([cpu | cuda | opencl]) used by the rust
wrapper irrespective of arrayfire backends built by the build script.
Subsequently, this ensures only rust crate currently built uses one
particular backend.

added option to build conf file to choose arrayfire backend

---

src/algorithm/mod.rs
src/lib.rs
tests/hello_world.rs

All the C-API functions in `/af/algorithm.h` are in the
module `algorithm` which is re-exported from crate root
as if all functions are in the scope of crate `arrayfire`.

Added rust API for functions in af/algorithm.h

---

Cargo.lock
Cargo.toml
README.md
examples/helloworld.rs
src/algorithm/mod.rs
src/arith/mod.rs
src/array.rs
src/blas/mod.rs
src/data/mod.rs
src/defines.rs
src/device/mod.rs
src/dim4.rs
src/image/mod.rs
src/lapack/mod.rs
src/lib.rs
src/signal/mod.rs
src/statistics/mod.rs
src/util.rs
src/vision/mod.rs
tests/hello_world.rs

This PR will include API related to the following headers:
* util
* arith
* data
* signal
* blas
* vision
* lapack
* image
* defines

Other headers

---

Cargo.toml
build.conf
examples/helloworld.rs
examples/histogram.rs
examples/pi.rs
examples/snow.rs
src/arith/mod.rs
src/defines.rs
src/graphics.rs
src/image/mod.rs
src/lib.rs
src/util.rs

* wrapper for graphics API from arrayfire
* Fix in image::{medfilt, minfilt, maxfilt} API
* Modified ColorMap enum to use C representation
* Corrections to examples to reflect new changes
* New graphics examples: snow(noise), histogram

graphics module

---

examples/helloworld.rs
examples/histogram.rs
examples/pi.rs
src/arith/mod.rs

This will allow all the operands to toggle the batch flag as necessary.

allow batch operands on binary functions

---

build.rs

- Fixes https://github.com/arrayfire/arrayfire-rust/issues/18 (doesn't use frameworks, but it does build and run on my MBP w/ ATI Radeon HD 6750M)
- Fixes issue with CPU BLAS F77 issue.

resolve osx build error with opencl and fix f77 issue

---

src/graphics.rs

Works every time now.
Tested by plotting many times at different window resolutions/titles and via:
```rust
loop {
wnd.draw_plot(&af::range(values.dims().unwrap().clone()
, 0, af::Aftype::F32).unwrap(), &values, None);
for i in 0..100 {
wnd.set_title(i.to_string());
}
if wnd.is_closed().unwrap() == true { break; }
}
```

use CString and to_bytes_with_nul to be C compatible with \0

---

Cargo.toml
README.md
build.conf
build.rs
examples/unified.rs
src/defines.rs
src/device/mod.rs
src/lib.rs

@9prady9 : Can you test opencl on linux? For some reason my linux box isn't building libafopencl. It should work as expected though. It **does** work fine on OSX though :)
```bash
Running `target/debug/examples/unified`
There are 2 available backends
ArrayFire v3.2.0 (CPU, 64-bit Linux, build c607f62)
[0] Intel: Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz Max threads(12) 
Create a 10-by-10 matrix of random floats on the compute device
No Name Array
[10 10 1 1]
0.0000     0.3835     0.4175     0.9103     0.2470     0.7665     0.9047     0.5007     0.8278     0.2332 
0.1315     0.5194     0.6868     0.7622     0.9826     0.4777     0.5045     0.3841     0.1254     0.3063 
0.7556     0.8310     0.5890     0.2625     0.7227     0.2378     0.5163     0.2771     0.0159     0.3510 
0.4587 …
```

Add unified API support and fix the build mechanism appropriately.

---

build.conf
build.rs

It's a little ridiculous that we don't check the lib dir. 
Added this logic (i.e. check lib64 first, then lib).
Also test results for when AF_PATH is not set is a little more meaningful now:
```bash
➜  arrayfire-rust git:(master) ✗ cargo run --verbose --example unified
Compiling libc v0.1.12
Running `rustc /Users/jramapuram/.cargo/registry/src/github.com-0a35038f75765ae4/libc-0.1.12/rust/src/liblibc/lib.rs --crate-name libc --crate-type lib -g --cfg feature=\"cargo-build\" --cfg feature=\"default\" -C metadata=29adb837ec836726 -C extra-filename=-29adb837ec836726 --out-dir /Users/jramapuram/projects/arrayfire-rust/target/debug/deps --emit=dep-info,link -L dependency=/Users/jramapuram/projects/arrayfire-rust/target/debug/deps -L dependency=/Users/jramapuram/projects/arrayfire-rust/target/deb …
```

remove the lib directory dependency from conf and add a message for when AF_PATH is not set

---

Cargo.toml
examples/helloworld.rs
examples/pi.rs
examples/snow.rs
examples/unified.rs
src/array.rs
src/backend.rs
src/data/mod.rs
src/defines.rs
src/device/mod.rs
src/graphics.rs
src/image/mod.rs
src/index.rs
src/lapack/mod.rs
src/lib.rs
src/macros.rs
src/util.rs
src/vision/mod.rs

Fixes #58 
More detailed information on the new release can be found at the
following URL
https://github.com/arrayfire/arrayfire/releases/tag/v3.3.0

API Catchup to 3.3.0 version

---

src/dim4.rs

Very annoying doing:
```rust
if arr.dims().unwrap().get().clone() == arr2.dims().unwrap().get().clone() {}
```
Also debug offers:
```rust
println!("dims = {:?}", arr.dims().unwrap());
```

Add support for partialeq & debug to dim4

---

src/defines.rs

This pull adds `Debug` and `PartialEq` to all the available af enums. 
I had one done earlier for just one. This covers the rest.
- Debug: adds ability to pretty-print enum
- PartialEq: adds ability to do a==b?  and a!=b

add clone and partialeq to all enums

---

src/array.rs
src/vision/mod.rs

Currently, calling accessor methods on a Features object causes a crash due to a double free.
A (reasonably) minimal example of this problem is demonstrated in the following program:
```rust
// file: af_bug_mwe.rs
extern crate arrayfire as af;
use std::mem;
fn main() {
af::set_device(0);
af::info();
// Load the test image: http://www.smufl.org/wp-content/uploads/M3.jpeg
let file_name = String::from("../../smufl-november2-test.jpg");
let img_grey = af::load_image(file_name, false).unwrap();
{
let features = af::fast(&img_grey, 20.0, 9, true, 0.05, 10).unwrap();
let num_features = features.num_features().unwrap() as usize;
println!("num_features: {:?}", num_features);
let af_xpos = features.xpos().unwrap();
println!("num_elements: {:?}", af_xpos.elements().unwrap());
// unsafe { …
```

Retain the arrays returned from Features's accessors

---

src/graphics.rs

Colormaps are not currently working because layout of the `Cell` structure doesn't match its version in arrayfire. Also there are some potential bugs because Rust's non null-terminated strings were passed to C.
This pull request fixes this. I also simplified code in graphics.rs where other strings were passed to C.

Fix colormaps

---

src/arith/mod.rs
src/data/mod.rs
src/defines.rs
src/lib.rs

New data generation functions and Neg trait implementation

---

src/arith/mod.rs

Additional arithmetic ops/traits implementations for Array and &Array

---

examples/helloworld.rs
src/device/mod.rs
src/lib.rs
src/util.rs

I've just added the linking and interface bit for `af_info_string` (also `af_free_host` and `af_alloc_host`). However, I'm not a 100% sure whether I need to call `af_free_host` and whether I'm doing that correctly, so definitely someone should take a look at that. 
Following the discussion on the forum [here](https://users.rust-lang.org/t/c-char-to-str-or-string/9417/9) in order to make `Rust` copy the string into rust allocated space I'm using `to_str().to_owned()` rather than `into_string()` and freeing the arrayfire buffer.

Added info_string

---

examples/helloworld.rs
src/device/mod.rs
src/lib.rs

Sorry, this should have been part of the previous, but was a bit busy.
One caveat is that I assumed that the commit string is truly static, so I return `Cow<'static, str>`. Also, I notice that the name of the platform has underscores `Intel(R)_Core(TM)_i7-4600U_CPU_@ 2.10GHz` so the question is should those be replaced by spaces or kept like that.

Added `get_revision` and `device_info`

---

build.rs
src/array.rs

Add more lib dir search options for build script

---

Cargo.toml
build.rs

Remove rustc_serialize in favor of Serde crate

---

src/random/mod.rs

Fixes #162 
Please let me know if, as per my question in #162, I'm misunderstanding some subtlety and attempting to change intended behaviour.

Take a shared reference instead of ownership in random::random_uniform() and random::random_normal()

---

src/algorithm/mod.rs
src/array.rs
src/data/mod.rs
src/defines.rs
src/graphics.rs
src/image/mod.rs
src/lapack/mod.rs
src/random/mod.rs
src/signal/mod.rs
src/sparse/mod.rs
src/statistics/mod.rs
src/util.rs
src/vision/mod.rs

Fix Rust enum repr qualification

---

examples/conway.rs
src/arith/mod.rs

Fix comparison functions output type

---

src/lib.rs
src/util.rs

Publicize internal traits to let users write generic fns

---

src/data/mod.rs

Fixes #202 
@srenevey How about the updated API ? Also, do take a look at how new API handles it's second argument.

Fix second argument of reorder API to be more clear

---

Cargo.toml
examples/helloworld.rs
examples/histogram.rs
examples/snow.rs
src/arith/mod.rs
src/backend.rs
src/defines.rs
src/dim4.rs
src/error.rs
src/graphics.rs
src/image/mod.rs
src/index.rs
src/seq.rs
tests/error_handler.rs
tests/scalar_arith.rs

There is one exception however - rust wrapper of arrayfire
panics whenever string arguments fail for whatever reason. In
such cases, we catch all errors to call `panic!`. This is one
lint that has been skipped.
Partially addresses #37

Address all clippy warns/errors

---

src/index.rs

Also, refactored docs examples to remove deprecated use of Indexer::new.

Elaborate is_batch param of set_index trait method

---

.github/workflows/ci.yml
src/error.rs

Fix unchecked string creation from ffi return value

---

src/data/mod.rs
tests/data.rs
tutorials-book/src/getting_started.md

Fix reorder_v2 axes computation

---

src/data/mod.rs
tests/data.rs

Added more illustrations to example code
Fixes #217

Improve reorder_v2 function documentation

---

src/array.rs

Added both a basic use case example and a generic use case example illustrated by a function.

Added examples for `arrayfire::host`

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/build_error.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/performance_issue.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE/documentation.md
.github/PULL_REQUEST_TEMPLATE/generic_pr_template.md
.github/PULL_REQUEST_TEMPLATE/new_example.md
.github/workflows/ci.yml
src/dim4.rs
src/macros.rs
tests/index_macro.rs
tests/seq_macro.rs

Helper macros for indexing operation, creation of dim4 and sequence objects

---

src/core/arith.rs
src/core/array.rs

Add missing bit shift trait impls for Array by unsigned integer types

---

src/core/device.rs
src/core/macros.rs

Expose pinned(non-pageable memory) alloc and free functions

---

src/core/macros.rs
tutorials-book/src/indexing.md

Fixes #197 
This macro provides some syntactic sugar hiding the logic that involves
creationg of Indexer object and then setting the indexing objects for
interested axes for a given Array.
Updated indexing tutorial in mdbook with examples using macros also.
Screenshots how the sample codes(from mdbook) are shown in the below comments.

New macro, equation, to help modify Array using Seq and/or Array

---

Cargo.toml
examples/pi.rs
src/algorithm/mod.rs
src/core/util.rs
tests/scalar_arith.rs

Use appropriate output type for reduce all ops

---

src/core/array.rs
src/core/data.rs
src/core/device.rs
src/core/index.rs

set_row and pad function fixes

---

README.md
src/core/macros.rs

New macros: constant, randu and randn

---

src/core/array.rs
src/core/event.rs
src/core/index.rs
src/core/random.rs
src/vision/mod.rs
tutorials-book/src/SUMMARY.md
tutorials-book/src/multi-threading.md

Added a new threading tutorial with code examples illustrating how to share Array across threads.

Enable thread-safety marker traits for Structs

---

src/algorithm/mod.rs

Fix return type trait bound on reduce all functions

---

.github/workflows/ci.yml
Cargo.toml
README.md
cuda-interop/Cargo.toml
cuda-interop/examples/cuda_af_app.rs
opencl-interop/Cargo.toml
opencl-interop/examples/custom_kernel.rs
src/core/array.rs
src/core/defines.rs
src/core/dim4.rs
src/core/random.rs
src/core/seq.rs

- Update ci to run serde tests
- Add serialization support for Enums
- Structs with serde support added
- Structs without serde support
- Features - currently not possible as `af_features` can't be recreated from individual `af_arrays` with current upstream API
- Indexer - not possible with current API. Also, any subarray when fetched to host for serialization results in separate owned copy this making serde support for this unnecessary.
- Callback
- Event
- Window
Fixes #221

Add optional serde serialization support

---

examples/helloworld.rs
src/core/index.rs
tutorials-book/src/indexing.md

Also add information about negative indices in indexing tutorial
Fixes #257

Fix negative indexing in row/col/slice functions

---

src/core/index.rs
src/core/seq.rs
src/core/util.rs

Restrict type of Arrays that can be used for indexing

---

src/core/data.rs

A tiny change to avoid an unnecessary heap allocation in `reorder_v2`.
First time contributor, just wanted to say thank you for the project. It's awesome to have such a useful and powerful numerical library with Rust bindings :100:

Avoid memory allocation in reorder_v2

---

src/core/arith.rs
src/core/data.rs
src/core/util.rs

This clarify relationship of traits (see #264 ).

Remove macros from some trait implementation

---

src/algorithm/mod.rs
src/core/data.rs
src/core/index.rs
src/core/macros.rs

Call set_device in tests for valid cuda context in threaded runs

---

src/core/util.rs
src/lib.rs

This prevents users from adding their own implementations for traits defined by ArrayFire Rust crate to help ease using arrayfire.
This shouldn't break any User code as long as user code is not using our crate's traits made public for for writing generic functions that can take `Array`s

Seal HasAfEnum, Fromf64 and extended traits

---

src/core/array.rs

This is safe because values of a type `Array<T>` where `T` is *not* `af::HasEnum` cannot be produced by a user anyway.
Pros: this trick allows library users to make their own struct definitions "lightweight" as well (as suggested by the [Rust API guidelines](https://rust-lang.github.io/api-guidelines/future-proofing.html#c-struct-bounds)).
Cons: the bound has to be removed from the Drop implementation as well (which is fine but perhaps counter intuitive)

Remove trait HasEnum from struct definition Array<T>

---

src/core/array.rs
src/core/dim4.rs

Code to illustrate the debug output
```rust
let a = randu!(3, 3);
let b = randu!(3, 3);
af_print!("a", a);
println!("a {:?}", &a);
println!("a {:#?}", &a);
println!("b {:?}", &b);
println!("b {:#?}", &b);
```
Sample Output
```
a
[3 3 1 1]
0.6010     0.2126     0.2864 
0.0278     0.0655     0.3410 
0.9806     0.5497     0.7509 
a Array { dtype: F32, shape: [3, 3, 1, 1], af_array: 0x560e508ba330 }
a Array {
dtype: F32,
shape: [3, 3, 1, 1],
data: [
0.6009535,
0.027758777,
0.9805506,
0.21263224,
0.06546384,
0.5496738,
0.28638768,
0.34101695,
0.7508749,
],
}
b Array { dtype: F32, shape: [3, 3, 1, 1], af_array: 0x560e503c1cb0 }
b Array {
dtype: F32,
shape: [3, 3, 1, 1],
data: [
0.41050708,
0.15832818,
0.3712476,
0.3543455,
0.6450288,
0.9674888,
0.36364043,
0.41647816,
0.5814448,
],
}
```

Format debug trait output

---

src/algorithm/mod.rs
src/core/arith.rs
src/core/array.rs
src/image/mod.rs
src/signal/mod.rs
src/statistics/mod.rs
src/vision/mod.rs

Earlier, these functions were using binary_func macro which picks output based on the input arrays types. However, as these are logical operations which always result in boolean output, the correct macro to use for this is overloaded_logic_func.
With this fix, ::and, ::or and ::neq functions have acquired an additional feature i.e. the user can also use scalars as one of the inputs of these functions.
Fixes #291

Fix output array for logical ops AND, OR and NEQ

---

Cargo.toml

I ran "cargo-test" and got 
`test src/algorithm/mod.rs - algorithm::max_ragged (line 1489) ... FAILED`
both before and after the version bump, so there aren't any regressions.
max_ragged seems to be failing because "_af_max_ragged" doesn't show up in the macos lib folder for whatever reason.
My IDE also formatted Cargo.toml,  but I can try and undo that if autoformatting is unwanted.
Fixes #293

Chore: bump outdated num and rustc versions

---

src/core/index.rs
src/core/macros.rs

Prior to this change, the following functions were not checking for additional
dimensional data beyond the dimension concerned with the particular
function.
- row
- col
- slice
- rows
- cols
- slices
- set_row
- set_col
- slice
- set_rows
- set_cols
- set_slices
Similar logic was missing in one particular matching pattern of view
macro which is also fixed in this change.
Few additional unit tests are added in macro and index module checking
for the pitfalls this change addresses
Fixes #295

Fix logic to sequence based indexing in row/col/slice functions

---

src/core/array.rs
src/core/dim4.rs
src/core/random.rs
src/core/seq.rs
src/image/mod.rs
tutorials-book/src/SUMMARY.md
tutorials-book/src/serde.md

Add a basic serilization/deserialization chapter to the tutorials book

---

README.md

Changed `lib64` to `lib`, valid for arrayfire 3.7.2
I think that I have successfully fixed the commit history on my fork so that this will work now. 
Fixes #303

Fixed typo in DYLY_LIBRARY_PATH in README

---

build.rs

This would have saved as a lot of debugging after moving the arrayfire folder (it only worked after a `cargo clean`).
See https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-env-changed for background info.

Rerun build script when `AF_PATH` changes

---

.gitignore
build.rs
examples/helloworld.rs
examples/neural_network.rs
src/core/arith.rs
src/core/array.rs
src/core/index.rs
src/core/macros.rs
tests/error_handler.rs

Fix clippy warnings

---

.github/workflows/ci.yml
build.rs

Fixes #308
Also:
- warn if backend files exist, but are not accessible (e.g. because access is denied).
- improves the formatting of errors and warnings
- print warnings to stderr instead of stdout
Cargo only shows the stderr/stdout of build scripts if they fail. So the new warnings do not clutter the output of successful builds.
Example output when a folder is inaccessible:
```
Compiling arrayfire v3.8.0 (/workspaces/arrayfire-rust)
error: failed to run custom build command for `arrayfire v3.8.0 (/workspaces/arrayfire-rust)`
Caused by:
process didn't exit successfully: `/workspaces/arrayfire-rust/target/debug/build/arrayfire-09f04fa2319aeba4/build-script-build` (exit status: 1)
--- stdout
cargo:rerun-if-env-changed=AF_PATH
--- stderr
WARNING: USE_LIB is defined, but AF_PATH is not found. …
```

Error in build script when no backends are found
